blog/urls.py
from django.urls import path
from blog.views import (
	create_blog_view,
	detail_blog_view,
	edit_blog_view,
)

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit/', edit_blog_view, name="edit"),
 ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls import url
from uploader import views
from blog import urls
from polls import urls
from pages import urls
#from accountss import urls
from accountss.views import registration_view, logout_view,login_view,account_view,must_authenticate_view
from blog.views import create_blog_view,detail_blog_view,edit_blog_view,get_blog_queryset
#from bllog import urls

#from bllog.views import create_blog_view,detail_blog_view,edit_blog_view,get_blog_queryset

from personal.views import home_screen_view
from django.contrib.auth import views as auth_views
# from accountss import urls

#from django.conf.urls import url

# from mysite import settings





from . import views
from rest_framework import routers
from .views import UserViewSet
router = routers.SimpleRouter(trailing_slash=False)
router.register(r'users', UserViewSet)

from django.views.generic import TemplateView
#admin.site.site_header= "Project Progress Website"
admin.site.site_header= "MunchySite | MunchyTeam"

#from django.urls import path, include
#from django.conf.urls import url, include
#from rest_framework import routers
#from .views import UserViewSet

urlpatterns = [
    re_path(r'^', include(router.urls)),
    path('admin/', admin.site.urls),
    path('user/account/', views.account_holder),
    path('blogposts/', views.munchy_blog_post),
    path('apps/',views.munchy_apps),
    path('', views.home),
    path('admins/', views.realhomepage),
    #path('', TemplateView.as_view(template_name="homepage.html"), name="realhomepage"),
    path('old-home', TemplateView.as_view(template_name="Home.html")),
    path('home3', views.home),
   # path('firstview', TemplateView.as_view(template_name="firstview.html")),
     path('bank-menu', views.bank_menu),# TemplateView.as_view(template_name="firstview.html")),
     path('bank', views.bank),#TemplateView.as_view(template_name="logon2.html")),

    path('progress', views.progress),
    path('progress/', include('progress.urls')),
    path('test/', views.test),
    path('navigation/', views.navigation),
    path('links/', views.navigation),
   path('veriosn', TemplateView.as_view(template_name="versions.html")),
   path('accounts/', include('allauth.urls')),
    #   path('bank/accounts/', include('allauth.urls')),
    re_path(r'^theuploader/$', views.main, name='main'),
    #url(r'/^$', views.main, name='main'),
    re_path(r'^uploader/media/$', views.simple_upload, name='simple_upload'),
    path('dev-tools', TemplateView.as_view(template_name="dev-tools.html")), 
    path('navigation', TemplateView.as_view(template_name="navigation.html")),
    path('navigation/specific-header', TemplateView.as_view(template_name="specific-header.html")),
    path('ml/', TemplateView.as_view(template_name="logedin.html")),
  path('CSerror', views.CSRF_ERROR),
  path('munchy2', TemplateView.as_view(template_name="logon2.html")),
  path('munchy3', TemplateView.as_view(template_name="logon3.html")),
    path('vbucks', TemplateView.as_view(template_name="rickroll3.html")),
      path('free-robux', TemplateView.as_view(template_name="rickroll3.html")),
       path('rewards', TemplateView.as_view(template_name="rewards3.html")),
      path('money', TemplateView.as_view(template_name="rickroll3.html")),
  path('blogs/', include('blog.urls')),
  path('polls/', include('polls.urls')),
  path('polling2/', include('pages.urls')),

  # path('accountss/', include('accountss.urls')),
   # url(r'^upload-tool/$', views.main, name='main'),
  #  url(r'^uploader/media/$', views.simple_upload, name='simple_upload'),
   # url(r'^media/documents/test.txt$', views.main, name='simple_upload'),
   # url(r'^main/$', views.main, name='main'),
   # url(r'^downloads/$', views.simple_upload, name='simple_upload'),
   path('blogs/', home_screen_view, name="home"),
    path('blogss/account/', account_view, name="account"),
    path('blogs/admin/', admin.site.urls),
    path('blog/', include('blog.urls', 'blog')),
    path('blogs/login/', login_view, name="login"),
    path('blogs/logout/', logout_view, name="logout"),
	path('blogs/must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('blogs/register/', registration_view, name="register"),
#asdfasdf
 # path('answers/', include('bllog.urls')),
  # path('accountss/', include('accountss.urls')),
   # url(r'^upload-tool/$', views.main, name='main'),
  #  url(r'^uploader/media/$', views.simple_upload, name='simple_upload'),
   # url(r'^media/documents/test.txt$', views.main, name='simple_upload'),
   # url(r'^main/$', views.main, name='main'),
   # url(r'^downloads/$', views.simple_upload, name='simple_upload'),
 #  path('answers/', home_screen_view, name="home"),
 #   path('answers/account/', account_view, name="account"),
  #  path('answers/admin/', admin.site.urls),
 #   path('answers/', include('bllog.urls', 'blog')),
 #   path('answers/login/', login_view, name="login"),
  #  path('answers/logout/', logout_view, name="logout"),
#	path('answers/must_authenticate/', must_authenticate_view, name="must_authenticate"),
 #   path('answers/register/', registration_view, name="register"),
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('blogs/password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('user/password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('blogs/password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('blogs/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('blogs/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('blogs/reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),

]


if settings.DEBUG==True:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
   #urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_URL)
   #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'mysite.views.munchy404'
handler404 = 'mysite.views.munchy500'
 # how can we implement this: https://www.youtube.com/watch?v=v5FWAxi5QqQ look at timestamp 7:18. I dont know how to implement that in html. #no idea help 
  
    
    #path('home/', ) # this wont work i think.
  

    

       

blog/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver

def upload_location(instance, filename):
	file_path = 'blog/{author_id}/{title}-{filename}'.format(
				author_id=str(instance.author.id),title=str(instance.title), filename=filename)
	return file_path


class BlogPost(models.Model):
	title 					= models.CharField(max_length=50, null=False, blank=False)
	body 					= models.TextField(max_length=5000, null=False, blank=False)
	image		 			= models.ImageField(upload_to=upload_location, null=True, blank=True)
	date_published 			= models.DateTimeField(auto_now_add=True, verbose_name="date published")
	date_updated 			= models.DateTimeField(auto_now=True, verbose_name="date updated")
	author 					= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	slug 					= models.SlugField(blank=True, unique=True)

	def __str__(self):
		return self.title

@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False) 

def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)

blog/forms.py
from django import forms

from blog.models import BlogPost 


class CreateBlogPostForm(forms.ModelForm):

	class Meta:
		model = BlogPost
		fields = ['title', 'body', 'image']


class UpdateBlogPostForm(forms.ModelForm):

	class Meta:
		model = BlogPost
		fields = ['title', 'body', 'image']

	def save(self, commit=True):
		blog_post = self.instance
		blog_post.title = self.cleaned_data['title']
		blog_post.body = self.cleaned_data['body']

		if self.cleaned_data['image']:
			blog_post.image = self.cleaned_data['image']

		if commit:
			blog_post.save()
		return blog_post

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.http import HttpResponse

from blog.models import BlogPost
from blog.forms import CreateBlogPostForm, UpdateBlogPostForm
#from account.models import Account
# i killed it 
from accountss.models import Account
from accountss.views import must_authenticate_view
def create_blog_view(request):

	context = {}
# don not change anything below I am working on the thingy you want to change. 
  #can i run djanog 3.2.11
  # sure idc.
	user = request.user
	if not user.is_authenticated:
		return render(request, 'account/must_authenticate.html', {})
	form = CreateBlogPostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit=False)
		#author = Account.objects.filter(email=user.username).first()
    #author = request.user
		obj.author = request.user
    
		obj.save()
		form = CreateBlogPostForm()

	context['form'] = form

	return render(request, "blog/create_blog.html", context)


def detail_blog_view(request, slug):

	context = {}

	blog_post = get_object_or_404(BlogPost, slug=slug)
	context['blog_post'] = blog_post

	return render(request, 'blog/detail_blog.html', context)



def edit_blog_view(request, slug):

	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect("must_authenticate")

	blog_post = get_object_or_404(BlogPost, slug=slug)

	if blog_post.author != user:
		return HttpResponse('You are not the author of that post.')

	if request.POST:
		form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=blog_post)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "Updated"
			blog_post = obj

	form = UpdateBlogPostForm(
			initial = {
					"title": blog_post.title,
					"body": blog_post.body,
					"image": blog_post.image,
         # "author1": blog_post.author,
			}
		)

	context['form'] = form
	return render(request, 'blog/edit_blog.html', context)


def get_blog_queryset(query=None):
	queryset = []
	queries = query.split(" ") # python install 2019 = [python, install, 2019]
	for q in queries:
		posts = BlogPost.objects.filter(
				Q(title__icontains=q) | 
				Q(body__icontains=q) 
       # Q(author1__icontains=q)        
			).distinct()

		for post in posts:
			queryset.append(post)

	return list(set(queryset))	

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang=en>

<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
</head>

<body>
{% include 'snippets/base_css.html' %}
{% include 'snippets/header.html' %}

<!-- Body -->
<style type="text/css">
	.main{
		min-height: 100vh;
		height: 100%;
	}
</style>
<div class="main text-light">
	{% block content %}

	{% endblock content %}
</div>
<!-- End Body -->

{% include 'snippets/footer.html' %}

</body>


</html>

blog/templates/blog/create_blog.html
{% extends 'blog/base.html' %}


{% block content %}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}
</style>

<div class="container text-light">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label class="text-light" for="id_title">Title</label>
					<input class="form-control bg-dark text-light" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group text-light">
					<label for="id_body">Content</label>
					<textarea class="form-control bg-dark text-light" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." required></textarea>
				</div>

				<!-- Image -->
				<div class="form-group">
					<label class="text-light" for="id_image">Image</label>
					<input class="text-light" type="file" name="image" id="id_image" accept="image/*" >
				</div>

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
			</form>	
		</div>
	</div>
</div>




{% endblock content %}

blog/templates/blog/detail_blog.html
{% extends 'blog/base.html' %}


{% block content %}


<style type="text/css">
	.card{
		max-width: 700px;
	}
	.card-body{
		padding: 20px;
	}
</style>

<div class="container">
	<div class="row">

		<!-- Blog Post -->
		<div class="card m-auto  bg-dark text-light">
			<img class="card-img-top" src="{{blog_post.image.url}}">
			<div class="card-body mt-2 mb-2">
			  <h2 class="card-title">{{blog_post.title}}</h2>
			  <p class="card-text">{{blog_post.body|safe}}</p>
			  {% if blog_post.author == request.user %}
			  	<a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-primary">Update</a>
			  {% endif %}
			</div>
			<div class="card-footer text-light">
			  Updated on {{blog_post.date_updated}} by {{blog_post.author.username}}
			</div>
		</div>
	</div>
</div>

	

{% endblock content %}

blog/templates/blog/edit_blog.html
{% extends 'blog/base.html' %}


{% block content %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group ">
					<label for="id_title" class=" text-light">Title: </label>
					<input class="form-control text-light bg-dark" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body" class=" text-light">Content:</label>
					<textarea class="form-control text-light bg-dark"  rows="10" type="text" name="body" id="id_body" placeholder="This post is about..." 
					required>{{form.initial.body}}</textarea>
				</div>

				<!-- Image -->
        	<label for="id_image" class=" text-light">Image: </label>
				<div class="form-group image-group" id="id_image_group">
          {% if form.initial.image %}
					<img class="img-fluid image card" src="{{form.initial.image.url}}" id="id_image_display">
          {% endif %}
					  <div class="middle">
					    <div class="text text-light" class=" text-light"">Change image</div>
					  </div>
				</div>
				<input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)" class="text-light">
				

				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>	
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
    	document.getElementById('id_image_file').click();
    };

	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_image_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}
</script>

{% endblock content %}